#uninstall nginx using yaml in ansible

- name: uninstall and stop the nginx
  hosts: mongodb
  become: true
  tasks:
  - name: uninstall nginx
    ansible.builtin.yum:
      name: nginx
      state: absent
    
   