- name: inastall and uninstall packages using loops
  hosts: localhost
  become: true
  tasks:
    - name: inastall and uninstall packages
      ansible.builtin.yum:
        name: "{{item.name}}"
        state: "{{item.state}}"
      loop:
      - {name: 'nginx', state: 'present'}
      - {name: 'git', state: 'absent'}
      - {name: 'docker', state: 'absent'}   
