#loops in ansible

- name:
  hosts: localhost
  become: true
  tasks:
  - name: install package
    ansible.builtin.ping:
      name: "{{item}}"
      state: installed
    loop:
      - nginx
      - git