#loops in ansible

- name:
  hosts: localhost
  become: true
  tasks:
  - name: install packages using loop
    ansible.builtin.yum:
      name: "{{item}}"
      state: installed
    loop:
      - nginx
      - git